// tethys-ui-react/src/main/frontend/components/header/Header.js
/**
 * Created by bnjm on 12/17/16.
 */
import React from 'react';
import logo from '../../logo.svg'
import './Header.css';

const Header = () => {
    return (
        <div className="App-header">
            <img src={logo} className="App-logo" alt="logo"/>
            <h2>Tethys ReactJS</h2>
        </div>
    );
};
export default Header;

// tethys-ui-angular2/src/main/frontend/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  title: string = 'Tethys Angular 2';

  constructor() { }

  ngOnInit() {
  }

}

<div class="page-header">
  <img class="ng2logo" src="../../assets/img/angular.svg">
  <h4>{{title}}</h4>
</div>
